<?php

namespace ContainerG4sC7gf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ji7KCYFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ji7KCYF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ji7KCYF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', true],
        ], [
            'personneRepository' => 'App\\Repository\\PersonneRepository',
        ]);
    }
}
