<?php

namespace ContainerG4sC7gf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneJsonServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PersonneJsonService' shared autowired service.
     *
     * @return \App\Service\PersonneJsonService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PersonneJsonService.php';

        return $container->privates['App\\Service\\PersonneJsonService'] = new \App\Service\PersonneJsonService((\dirname(__DIR__, 3).'/contact/'));
    }
}
