#index:
#    path: /
#    controller: App\Controller\DefaultController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::index

adminMessages:
  path: /admin/messages
  controller: App\Controller\Admin\AdminController::checkMessages

processMessages:
  path: /admin/processMessages
  controller: App\Controller\Admin\AdminController::processMessages

