<?php

namespace ContainerOMuLBd5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WAB5lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._wA_b5l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._wA_b5l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personneJsonService' => ['privates', 'App\\Service\\PersonneJsonService', 'getPersonneJsonServiceService', true],
            'personneService' => ['privates', 'App\\Service\\PersonneService', 'getPersonneServiceService', true],
        ], [
            'personneJsonService' => 'App\\Service\\PersonneJsonService',
            'personneService' => 'App\\Service\\PersonneService',
        ]);
    }
}
