<?php

namespace ContainerOMuLBd5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PersonneService' shared autowired service.
     *
     * @return \App\Service\PersonneService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PersonneService.php';

        return $container->privates['App\\Service\\PersonneService'] = new \App\Service\PersonneService(($container->privates['App\\Repository\\PersonneRepository'] ?? $container->load('getPersonneRepositoryService')));
    }
}
