<?php

namespace AC\ContactBundle\Repository;

/**
 * InternauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternauteRepository extends \Doctrine\ORM\EntityRepository
{

}
