<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4sC7gf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4sC7gf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG4sC7gf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG4sC7gf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG4sC7gf\App_KernelDevDebugContainer([
    'container.build_hash' => 'G4sC7gf',
    'container.build_id' => 'f8a6e3bf',
    'container.build_time' => 1625607072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4sC7gf');
